import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/message.dart';
import '../services/firebase_service.dart';

/// Provider for ChatService
final chatServiceProvider = Provider<ChatService>((ref) {
  return ChatService();
});

/// Firebase-based Chat Service
/// All chat/messaging functionality stays with Firebase for real-time updates
class ChatService {
  final CollectionReference _messagesCollection =
      FirebaseService.messagesCollection;

  /// Send a message (stores in Firebase)
  Future<String> sendMessage({
    required String matchId,
    required String senderId,
    required String senderName,
    required String text,
    MessageType type = MessageType.text,
  }) async {
    final message = Message(
      id: '', // Will be generated by Firestore
      matchId: matchId,
      senderId: senderId,
      senderName: senderName,
      text: text,
      timestamp: DateTime.now(),
      isRead: false,
      type: type,
    );

    final docRef = await _messagesCollection.add(message.toFirestore());
    return docRef.id;
  }

  /// Get messages for a match (real-time stream)
  Stream<List<Message>> getMessages(String matchId) {
    return _messagesCollection
        .where('matchId', isEqualTo: matchId)
        .orderBy('timestamp', descending: true)
        .limit(100)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs.map((doc) => Message.fromFirestore(doc)).toList();
    });
  }

  /// Mark message as read
  Future<void> markAsRead(String messageId) async {
    await _messagesCollection.doc(messageId).update({'isRead': true});
  }

  /// Mark all messages in a match as read
  Future<void> markAllAsRead(String matchId, String currentUserId) async {
    final querySnapshot = await _messagesCollection
        .where('matchId', isEqualTo: matchId)
        .where('senderId', isNotEqualTo: currentUserId)
        .where('isRead', isEqualTo: false)
        .get();

    final batch = FirebaseFirestore.instance.batch();
    for (final doc in querySnapshot.docs) {
      batch.update(doc.reference, {'isRead': true});
    }
    await batch.commit();
  }

  /// Get unread message count for a match
  Future<int> getUnreadCount(String matchId, String currentUserId) async {
    final querySnapshot = await _messagesCollection
        .where('matchId', isEqualTo: matchId)
        .where('senderId', isNotEqualTo: currentUserId)
        .where('isRead', isEqualTo: false)
        .get();

    return querySnapshot.docs.length;
  }

  /// Get unread message count stream
  Stream<int> getUnreadCountStream(String matchId, String currentUserId) {
    return _messagesCollection
        .where('matchId', isEqualTo: matchId)
        .where('senderId', isNotEqualTo: currentUserId)
        .where('isRead', isEqualTo: false)
        .snapshots()
        .map((snapshot) => snapshot.docs.length);
  }

  /// Delete a message
  Future<void> deleteMessage(String messageId) async {
    await _messagesCollection.doc(messageId).delete();
  }

  /// Delete all messages for a match
  Future<void> deleteAllMessages(String matchId) async {
    final querySnapshot =
        await _messagesCollection.where('matchId', isEqualTo: matchId).get();

    final batch = FirebaseFirestore.instance.batch();
    for (final doc in querySnapshot.docs) {
      batch.delete(doc.reference);
    }
    await batch.commit();
  }

  /// Get last message for a match
  Future<Message?> getLastMessage(String matchId) async {
    final querySnapshot = await _messagesCollection
        .where('matchId', isEqualTo: matchId)
        .orderBy('timestamp', descending: true)
        .limit(1)
        .get();

    if (querySnapshot.docs.isEmpty) return null;
    return Message.fromFirestore(querySnapshot.docs.first);
  }

  /// Get last message stream
  Stream<Message?> getLastMessageStream(String matchId) {
    return _messagesCollection
        .where('matchId', isEqualTo: matchId)
        .orderBy('timestamp', descending: true)
        .limit(1)
        .snapshots()
        .map((snapshot) {
      if (snapshot.docs.isEmpty) return null;
      return Message.fromFirestore(snapshot.docs.first);
    });
  }
}
