// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcBXSDeBDZ97xuqmkMnnzfTdRkfLL5gIk',
    appId: '1:288500183974:web:fc2dd137f091dbcae9d567',
    messagingSenderId: '288500183974',
    projectId: 'petconnect-8e37d',
    authDomain: 'petconnect-8e37d.firebaseapp.com',
    storageBucket: 'petconnect-8e37d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC1jfC81iGC1pkAaDL_ZMP5RJ3nMXrwNw',
    appId: '1:288500183974:android:46671a1fbfb5b9f9e9d567',
    messagingSenderId: '288500183974',
    projectId: 'petconnect-8e37d',
    storageBucket: 'petconnect-8e37d.firebasestorage.app',
    databaseURL: 'https://petconnect-8e37d-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9hQSnWjzEhd6OJlsPtR0mviigjD-6er4',
    appId: '1:288500183974:ios:f2f5679cf43e94efe9d567',
    messagingSenderId: '288500183974',
    projectId: 'petconnect-8e37d',
    storageBucket: 'petconnect-8e37d.firebasestorage.app',
    iosBundleId: 'com.example.petCon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcBXSDeBDZ97xuqmkMnnzfTdRkfLL5gIk',
    appId: '1:288500183974:web:7c5a4799a23d9b8fe9d567',
    messagingSenderId: '288500183974',
    projectId: 'petconnect-8e37d',
    authDomain: 'petconnect-8e37d.firebaseapp.com',
    storageBucket: 'petconnect-8e37d.firebasestorage.app',
  );
}
